Adombisege/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/urls.py
from django.urls import path

from .views import *
app_name = 'website'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),
    path('add_to_cart/', AddToCartView.as_view(), name='add_to_cart'),
    path('collection/', CollectionView.as_view(), name='collection'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('faq/', FaqView.as_view(), name='faq'),
    path('my-cart/', MyCartView.as_view(), name='my-cart'),
    path('my-cart/remove_item/<int:item_id>/', RemoveCartItemView.as_view(), name='remove_item'),
    path('my-cart/update_quantity/<int:item_id>/', UpdateQuantityView.as_view(), name='update_cart_item'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('checkout/place-order/', PlaceOrderView.as_view(), name='place_order'),
    path('checkout/complete_order/', CompleteOrderView.as_view(), name='complete_order'),
    path('paypal-return/', paypal_return, name='paypal_return'),
    path('paypal-cancel/', paypal_cancel, name='paypal_cancel'),
    path('user-dashboard/', UserDashboardView.as_view(), name='user_dashboard'),
    path('user-dashboard/profile_update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),
    path('product-details/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.conf import settings
from paypalrestsdk import Payment
import paypalrestsdk
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.views.generic import CreateView
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from Adombisege.utils.decorators import MustLogin
from dashboard.forms import OrderAddressForm
from dashboard.models import Contact, Order, OrderAddressInfo, OrderItems, Product, Category, Cart, Region
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth import update_session_auth_hash
from django.utils.decorators import method_decorator

# paypalrestsdk.configure({
#     "mode": settings.PAYPAL_MODE,  # sandbox or live
#     "client_id": settings.PAYPAL_CLIENT_ID,
#     "client_secret": settings.PAYPAL_CLIENT_SECRET,
# })

class HomePageView(View):
    template_name = 'pages/home.html'
    
    def get(self, request):
        categories = Category.objects.all()[:3]
        products = Product.objects.filter(category__in=categories, status= 'Published').order_by('-created_at')[:20]
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0 
        context = {
            'categories' : categories,
            'products' : products,
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
        }
        return render(request, self.template_name, context)
    
class SearchView(View):
    template_name = 'pages/search_result.html'
    
    def get(self, request):
        user = request.user
        keyword = request.GET.get('keyword')
        category_id = request.GET.get('category')
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        if keyword:
            products = Product.objects.filter(Q(name__icontains=keyword) | Q(description__icontains=keyword) | Q(category__id=category_id), status= 'Published') if category_id else Product.objects.filter(Q(name__icontains=keyword) | Q(description__icontains=keyword), status= 'Published')
            paginator = Paginator(products, 12)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            categories = Category.objects.all()
            my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
            context = {
                'products' : page_obj,
                'my_cart' : my_cart,
                'categories' : categories,
                'cart_sub_total' : cart_sub_total,
            }
            return render(request, self.template_name,context)
    
class CollectionView(View):
    template_name = 'pages/collection.html'
    
    def get(self, request):
        user = request.user
        sort_by = request.GET.get('sort_by')
        category_name = request.GET.get('category_name')
        category_id = Category.objects.get(name=category_name).id if category_name else None
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        if sort_by or category_id:
            products = Product.objects.filter(status= 'Published')
            if category_id:
                products = products.filter(category_id=category_id)
            if sort_by == 'price_low_to_high':
                products = products.order_by('regular_price')
            elif sort_by == 'price_high_to_low':
                products = products.order_by('-regular_price')
            elif sort_by == 'newest_first':
                products = products.order_by('-created_at')
            elif sort_by == 'oldest_first':
                products = products.order_by('created_at')
            paginator = Paginator(products, 12)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            user = request.user
            my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
            categories = Category.objects.all()
            context = {
                'products' : page_obj,
                'my_cart' : my_cart,
                'categories' : categories,
                'cart_sub_total' : cart_sub_total,
            }
            return render(request, self.template_name,context)
        products = Product.objects.filter(status= 'Published').order_by('-created_at')
        paginator = Paginator(products, 20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        categories = Category.objects.all()
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        context = {
            'products' : page_obj,
            'categories' : categories,
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
        }
        return render(request, self.template_name,context)
    

class ContactView(View):
    template_name = 'pages/contact.html'
    
    def get(self, request):
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
            'categories' : categories
        }
        return render(request, self.template_name,context)
    
    def post(self, request):
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        if name and email and subject and message:
            Contact.objects.create(name=name, email=email, subject=subject, message=message)
            messages.success(request, 'Your message has been sent successfully!')
            return redirect('website:contact') 
        else:
            messages.error(request, 'An error occurred while sending your message. Please ensure all fields are filled out correctly.')
        
        # In case of errors, re-render the page with the existing form data
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'my_cart': my_cart,
            'cart_sub_total': cart_sub_total,
            'categories': categories,
            'name': name,
            'email': email,
            'subject': subject,
            'message': message
        }
        return render(request, self.template_name, context)
class AboutUsView(View):
    template_name = 'pages/about-us.html'
    
    def get(self, request):
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
            'categories' : categories
        }
        return render(request, self.template_name,context)
    
class FaqView(View):
    template_name = 'pages/faq.html'
    
    def get(self, request):
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
            'categories' : categories
        }
        return render(request, self.template_name,context)
    
class PrivacyPolicyView(View):
    template_name = 'pages/privacy_policy.html'
    
    def get(self, request):
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
            'categories' : categories
        }
        return render(request, self.template_name,context)
    
class ProductDetailView(View):
    template_name = 'pages/product_details.html'
    
    def get(self, request, pk):
        product = Product.objects.get(id=pk)
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'product' : product,
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
            'categories' : categories
        }
        return render(request, self.template_name,context)
    
class AddToCartView(View):
    @method_decorator(MustLogin)
    def post(self, request):
        user = request.user
        product_id = request.POST.get('product_id')
        size = request.POST.get('size')
        color = request.POST.get('color')
        quantity = int(request.POST.get('quantity'))
        product = Product.objects.get(id=product_id)
        # Check if the product is already in the user's cart
        cart_item = Cart.objects.filter(user=user, product=product).first()
        if cart_item:
            cart_item.quantity += quantity
            cart_item.save()
            messages.success(request, 'Product quantity updated successfully')

website/templates/includes/sections/category.html
{% load static %}
<section class="p-0">
    <div class="container">
        <div class="row overlio">
            {% for category in categories %}
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4">
                <div class="cats_caption_wrap">
                    <div class="cats_caption_thumb mb-2">
                        <a href="{% url 'website:collection' %}?category_name={{category.name}}" class="d-block"><img src="{{category.get_image}}" class="img-fluid rounded" alt="" /></a>
                    </div>
                    <div class="cats_caption text-center">
                        <h4 class="m-0">{{category.name}}</h4>
                        <span class="text-muted">{{category.get_product_count}} Collections</span>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

website/templates/includes/sections/deals.html
{% load static %}
<section class="bg-cover" style="background:url(static/website/assets/img/banner-c.jpg) no-repeat;" data-overlay="5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-8 col-lg-9 col-md-12 col-sm-12">

                <div class="deals_wrap text-center">
                    <h4 class="ft-medium text-light">Get up to -40% Off</h4>
                    <h2 class="ft-bold text-light">Only Summer Collections</h2>
                    <p class="text-light">
                        Visit our shop to see amazing creations from our designers. Get the best deals on our summer collections. Hurry up! Limited time offer.
                    </p>
                    <div class="mt-5">
                        <a href="{% url 'website:collection' %}" class="btn btn-white stretched-link">Start Shopping <i class="lni lni-arrow-right"></i></a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

website/templates/includes/sections/order_history.html
{% load static %}
{% if order_history %}
    {% for order in order_history %}
    <div class="ord_list_wrap border mb-4 mfliud">
        <div class="ord_list_head gray d-flex align-items-center justify-content-between px-3 py-3">
            <div class="olh_flex">
                <p class="m-0 p-0"><span class="text-muted">Order Number</span></p>
                <h6 class="mb-0 ft-medium">{{ order.order_id }}</h6>
            </div>
            <div class="olh_flex">
                <p class="mb-1 p-0"><span class="text-muted">Status</span></p>
                <div class="delv_status">
                    <span class="ft-medium small text-{% if order.status == 'Pending' %}warning{% elif order.status == 'Processing' %}info{% elif order.status == 'Approved' %}success{% elif order.status == 'Shipped' %}primary{% elif order.status == 'Delivered' %}success{% elif order.status == 'Returned' %}danger{% elif order.status == 'Cancelled' %}danger{% else %}dark{% endif %} bg-light-{% if order.status == 'Pending' %}warning{% elif order.status == 'Processing' %}info{% elif order.status == 'Approved' %}success{% elif order.status == 'Shipped' %}primary{% elif order.status == 'Delivered' %}success{% elif order.status == 'Returned' %}danger{% elif order.status == 'Cancelled' %}danger{% else %}dark{% endif %} rounded px-3 py-1">{{ order.status }}</span>
                </div>
            </div>
            <div class="olh_flex">
                <button class="btn btn-sm btn-secondary" data-order-id="{{ order.id }}" data-toggle="modal" data-target="#orderDetailsModal_{{ order.id }}">View</button>
            </div>
        </div>
        <div class="ord_list_body text-left">
            {% for item in order.get_order_items %}
            <div class="row align-items-center justify-content-center m-0 py-4 br-bottom">
                <div class="col-xl-5 col-lg-5 col-md-5 col-12">
                    <div class="cart_single d-flex align-items-start mfliud-bot">
                        <div class="cart_selected_single_thumb">
                            <a href="#"><img src="{{ item.product.image.url }}" width="75" class="img-fluid rounded" alt="{{ item.product.name }}"></a>
                        </div>
                        <div class="cart_single_caption pl-3">
                            <p class="mb-0"><span class="text-muted small">{{ item.product.category.name }}</span></p>
                            <h4 class="product_title fs-sm ft-medium mb-1 lh-1">{{ item.product.name }}</h4>
                            <p class="mb-2"><span class="text-dark medium">Size: {{ item.product.size }}</span>, <span class="text-dark medium">Color: {{ item.product.color }}</span></p>
                            <h4 class="fs-sm ft-bold mb-0 lh-1">GHC {{ item.product.get_price }}</h4>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-3 col-6">
                    <p class="mb-1 p-0"><span class="text-muted">Quantity</span></p>
                    <h4 class="fs-sm ft-bold mb-0 lh-1">{{ item.quantity }}</h4>
                </div>
                <div class="col-xl-4 col-lg-4 col-md-4 col-6">
                    <p class="mb-1 p-0"><span class="text-muted">Subtotal:</span></p>
                    <h6 class="mb-0 ft-medium fs-sm">{{ item.get_total }}</h6>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="ord_list_footer d-flex align-items-center justify-content-between br-top px-3">
            <div class="col-xl-3 col-lg-3 col-md-4 olf_flex text-left px-0 py-2 br-right">
                {% if order.status == 'Pending' %}
                <a href="#" class="ft-medium fs-sm"><i class="ti-close mr-2"></i>Cancel Order</a>
                {% endif %}
            </div>
            <div class="col-xl-9 col-lg-9 col-md-8 pr-0 py-2 olf_flex d-flex align-items-center justify-content-between">
                <div class="olf_flex_inner hide_mob">
                    <p class="m-0 p-0"><span class="text-muted medium">Paid using {{ order.payment_method }}</span></p>
                </div>
                <div class="olf_inner_right">
                    <h5 class="mb-0 fs-sm ft-bold">Total: {{ order.total_price }}</h5>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% include 'includes/modals/order_detail.html' %}
{% else %}
    <p>No order history available.</p>
{% endif %}

website/templates/includes/sections/payment_info.html
<!-- Payment method content goes here -->
<div class="row align-items-start">

    <!-- Single -->
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
        <div class="card-wrap gray rounded mb-4">
            <div class="card-wrap-header px-3 py-2 br-bottom d-flex align-items-center justify-content-between">
                <div class="card-header-flex">
                    <h4 class="fs-md ft-bold mb-1">Debit / Credit Card</h4>
                </div>
                <div class="card-head-last-flex">
                    <!-- Button -->
                    <a class="border p-3 bg-white circle text-dark d-inline-flex align-items-center justify-content-center" href="add-card.html"><i class="fas fa-pen-nib position-absolute"></i></a>
                    <!-- Button -->
                    <button class="border bg-white text-danger p-3 circle text-dark d-inline-flex align-items-center justify-content-center"><i class="fas fa-times position-absolute"></i></button>
                </div>
            </div>
            <div class="card-wrap-body px-3 py-3">
                <div class="pay-card mb-3">
                    <h5 class="fs-sm ft-bold mb-0">Card Number</h5>
                    <p>1470 **** **** 6325 (Visa)</p>
                </div>
                <div class="pay-card mb-3">
                    <h5 class="fs-sm ft-bold mb-0">Card Holder</h5>
                    <p>Dhananjay Preet</p>
                </div>

                <div class="pay-card mb-3">
                    <h5 class="fs-sm ft-bold mb-0">Expired</h5>
                    <p>January 2027</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Single -->
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
        <div class="card-wrap gray rounded mb-4">
            <div class="card-wrap-header px-3 py-2 br-bottom d-flex align-items-center justify-content-between">
                <div class="card-header-flex">
                    <h4 class="fs-md ft-bold mb-1">Debit / Credit Card</h4>
                </div>
                <div class="card-head-last-flex">
                    <!-- Button -->
                    <a class="border p-3 bg-white circle text-dark d-inline-flex align-items-center justify-content-center" href="add-card.html"><i class="fas fa-pen-nib position-absolute"></i></a>
                    <!-- Button -->
                    <button class="border bg-white text-danger p-3 circle text-dark d-inline-flex align-items-center justify-content-center"><i class="fas fa-times position-absolute"></i></button>
                </div>
            </div>
            <div class="card-wrap-body px-3 py-3">
                <div class="pay-card mb-3">
                    <h5 class="fs-sm ft-bold mb-0">Card Number</h5>
                    <p>8526 **** **** 1700 (Visa)</p>
                </div>
                <div class="pay-card mb-3">
                    <h5 class="fs-sm ft-bold mb-0">Card Holder</h5>
                    <p>Dhananjay Singh</p>
                </div>

                <div class="pay-card mb-3">
                    <h5 class="fs-sm ft-bold mb-0">Expired</h5>
                    <p>January 2027</p>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- row -->

<!-- row -->
<div class="row align-items-start">

    <!-- Single -->
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
        <div class="form-group">
            <a href="add-card.html" class="btn stretched-link borders full-width"><i class="fas fa-plus mr-2"></i>Add New Card</a>
        </div>
    </div>

</div>
<!-- row -->

website/templates/includes/sections/products.html
{% load static %}

{% if products %}
<section class="middle">
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <div class="sec_title position-relative text-center">
                    <h2 class="off_title">Trendy Products</h2>
                    <h3 class="ft-bold pt-3">Our Trending Products</h3>
                </div>
            </div>
        </div>

        <!-- row -->
        <div class="row align-items-center rows-products">

            <!-- Single -->
            
            {% for product in products %}
            <div class="col-xl-3 col-lg-4 col-md-6 col-6">
                <div class="product_grid card b-0">
                    <div class="badge bg-success text-white position-absolute ft-regular ab-left text-upper">{{product.tag}}</div>
                    <div class="card-body p-0">
                        <div class="shop_thumb position-relative">
                            <a class="card-img-top d-block overflow-hidden" href="{% url 'website:product_details' product.id %}"><img class="card-img-top" src="{{product.get_image}}" alt="..."></a>
                            <div class="product-hover-overlay bg-dark d-flex align-items-center justify-content-center">
                                <div class="edlio"><a href="#" data-toggle="modal" data-target="#quickview_{{product.id}}" class="text-white fs-sm ft-medium"><i class="fas fa-eye mr-1"></i>Quick View</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer b-0 p-3 pb-0 d-flex align-items-start justify-content-center">
                        <div class="text-left">
                            <div class="text-center">
                                <h5 class="fw-bolder fs-md mb-0 lh-1 mb-1"><a href="{% url 'website:product_details' product.id %}">{{product.name}}</a></h5>
                                <div class="elis_rty"><span class="ft-bold fs-md text-dark">GHC {{product.regular_price}}</span></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
                
        </div>
        <!-- row -->

        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <div class="position-relative text-center">
                    <a href="{% url 'website:collection' %}" class="btn stretched-link borders">Explore More<i class="lni lni-arrow-right ml-2"></i></a>
                </div>
            </div>
        </div>

    </div>
</section>
{% endif %}
    

website/templates/includes/sections/profile.html
<div class="row card align-items-center">
    <form action="{% url 'website:profile_update' %}" method="post" class="row m-0">
        {% csrf_token %}
        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
            <div class="form-group">
                <label class="small text-dark ft-medium">First Name</label>
                <input type="text" class="form-control" value="{{ user.first_name }}" name="fname"/>
            </div>
        </div>

        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
            <div class="form-group">
                <label class="small text-dark ft-medium">Last Name</label>
                <input type="text" class="form-control" value="{{ user.last_name }}" name="lname"/>
            </div>
        </div>

        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
            <div class="form-group">
                <label class="small text-dark ft-medium">Email</label>
                <input type="text" class="form-control" value="{{ user.email }}" disabled name="email"/>
            </div>
        </div>
        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
            <div class="form-group">
                <label class="small text-dark ft-medium">Phone Number</label>
                <input type="text" class="form-control" value="{{ user.phone_number }}" name="phone_number"/>
            </div>
        </div>
        <p class="col-xl-12 col-lg-12 col-md-12 col-sm-12 text-danger">
            You can change your password here. Please enter your current password and
            enter your new password twice to confirm.
        </p>
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
            <div class="form-group">
                <label class="small text-dark ft-medium">Current Password</label>
                <input type="password" class="form-control" name="current_password"/>
            </div>
        </div>
        
        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
            <div class="form-group">
                <label class="small text-dark ft-medium">New Password</label>
                <input type="password" class="form-control" name="password"/>
            </div>
        </div>
        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
            <div class="form-group">
                <label class="small text-dark ft-medium">Confirm New Password</label>
                <input type="password" class="form-control" name="confirm_password"/>
            </div>
        </div>

        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
            <div class="form-group">
                <button type="submit" class="btn btn-dark">Save Changes</button>
            </div>
        </div>
    </form>
</div>