Adombisege/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path

from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/',LoginView.as_view(),name='login'),
    path('register/',RegisterView.as_view(),name='register'),
    path('logout/',LogoutView.as_view(),name='logout')
]

website/urls.py
from django.urls import path

from .views import *
app_name = 'website'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),
    path('add_to_cart/', AddToCartView.as_view(), name='add_to_cart'),
    path('collection/', CollectionView.as_view(), name='collection'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('faq/', FaqView.as_view(), name='faq'),
    path('my-cart/', MyCartView.as_view(), name='my-cart'),
    path('my-cart/remove_item/<int:item_id>/', RemoveCartItemView.as_view(), name='remove_item'),
    path('my-cart/update_quantity/<int:item_id>/', UpdateQuantityView.as_view(), name='update_cart_item'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('checkout/place-order/', PlaceOrderView.as_view(), name='place_order'),
    path('checkout/complete_order/', CompleteOrderView.as_view(), name='complete_order'),
    path('paypal-return/', paypal_return, name='paypal_return'),
    path('paypal-cancel/', paypal_cancel, name='paypal_cancel'),
    path('user-dashboard/', UserDashboardView.as_view(), name='user_dashboard'),
    path('user-dashboard/profile_update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),
    path('product-details/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from .managers import UserManager

class User(AbstractUser):
    username = models.CharField(max_length=50,blank=True, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15)
    gender = models.CharField(max_length=10)
    is_active = models.BooleanField(default=True)
    is_customer = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'phone_number']
    
    objects = UserManager()
    
    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'
    
    def get_short_name(self):
        return self.first_name
    
    def has_perm(self, perm, obj=None):
        if self.is_superuser:
            return True
        return super().has_perm(perm, obj)

    def has_module_perms(self, app_label):
        if self.is_superuser:
            return True
        return super().has_module_perms(app_label)
    

dashboard/models.py
import random
import string
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='category/', null=True, blank=True)
    
    def get_image(self):
        if self.image:
            return self.image.url
            # return '/static/website/assets/men_category.png'
        else:
            return '/static/website/assets/img/category_image.png'

    def __str__(self):
        return self.name
    
    def get_product_count(self):
        return self.product_set.count()
    
    class Meta:
        verbose_name_plural = 'Categories'
        
class Size(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Product(models.Model):
    STOCK_STATUS_CHOICES = (
        ('In Stock', 'In Stock'),
        ('Out of Stock', 'Out of Stock'),
    )
    STATUS_CHOICES = (
        ('Published', 'Published'),
        ('Draft', 'Draft'),
    )
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='product/', null=True, blank=True)
    regular_price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sizes = models.ManyToManyField(Size)
    colors = models.ManyToManyField(Color)  # Many-to-Many relationship with Color
    tag = models.CharField(max_length=100, null=True, blank=True)
    stock_status = models.CharField(max_length=100, choices=STOCK_STATUS_CHOICES, default='In Stock')
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='Published')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def get_price(self):
        '''Returns the price of the product'''
        return self.discount_price if self.discount_price else self.regular_price
    
    
    def get_image(self):
        if self.image:
            return self.image.url
            # return '/static/website/assets/project3.png'
        else:
            return '/static/website/assets/img/product_image.png'

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Products'
    
class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()
    
    class Meta:
        verbose_name_plural = 'Contacts'


class Cart(models.Model):
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE,related_name='my_cart')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    color = models.CharField(max_length=10,blank=True, null=True)
    size = models.CharField(max_length=10,blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def get_total(self):
        '''Returns the total price of the order item'''
        # Check if the product has a discount
        if self.product.discount_price:
            return self.product.discount_price * self.quantity
        return self.product.regular_price * self.quantity if self.product.regular_price else 0
    
    def __str__(self):
        return f'{self.product.name} - {self.quantity}'
    
    @staticmethod
    def get_sub_total(user):
        '''Returns the total price of all items in the cart for a specific user'''
        cart_items = Cart.objects.filter(user=user)
        # if user has coupon applied
        # if cart_items.filter(coupon_applied=True).exists():
        #     return sum([item.get_discount_total() for item in cart_items])
        return sum([item.get_total() for item in cart_items])
    
class OrderItems(models.Model):
    user = models.ForeignKey('accounts.User',on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.product.name} - {self.quantity}'
    
    def get_total(self):
        '''Returns the total price of the order item'''
        # Check if the product has a discount
        if self.product.discount_price:
            return self.product.discount_price * self.quantity
        return self.product.regular_price * self.quantity if self.product.regular_price else 0
    
    @staticmethod
    def get_sub_total(user):
        '''Returns the total price of all items in the cart for a specific user'''
        cart_items = Cart.objects.filter(user=user)
        # if user has coupon applied
        # if cart_items.filter(coupon_applied=True).exists():
        #     return sum([item.get_discount_total() for item in cart_items])
        return sum([item.get_total() for item in cart_items])
    
    class Meta:
        verbose_name_plural = 'Order Items'
    
class Order(models.Model):
    def generate_order_id() -> str:
        '''Generates a unique order id'''
        sub = 'AC-'
        return sub + ''.join(random.choices(string.digits, k=8))
    
    ORDER_STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Processing', 'Processing'),
        ('Approved', 'Approved'),
        ('Shipped', 'Shipped'),
        ('Delivered', 'Delivered'),
        ('Returned', 'Returned'),
        ('Cancelled', 'Cancelled'),
    )
    PAYMENT_METHOD_CHOICES = (
        ('Cash', 'Cash'),
        ('Online', 'Online'),
    )
    PAYMENT_STATUS_CHOICES = (
        ('Not Paid', 'Not Paid'),
        ('Paid', 'Paid'),
        ('Pending', 'Pending'),
        ('Failed', 'Failed'),
    )
    order_id = models.CharField(max_length=20, default=generate_order_id, unique=True)
    user = models.ForeignKey('accounts.User', on_delete=models.PROTECT)
    order_items = models.ManyToManyField(OrderItems, related_name='order_items')
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    special_instructions = models.TextField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='Pending')
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, default='Cash')
    payment_status = models.CharField(max_length=20, choices=PAYMENT_STATUS_CHOICES, default='Not Paid')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'Order from {self.user} - {self.order_id} - {self.status}'
    
    def get_order_items(self):
        return self.order_items.all()
    
    def get_total_price(self):
        total = 0
        for item in self.order_items.all():
            total += item.product.price * item.quantity
        return total
    
    class Meta:
        verbose_name_plural = 'Orders'

class Region(models.Model):
    name = models.CharField(max_length=100)
    delivery_fee = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False, blank=True, null=True)
    
    def __str__(self):
        return self.name
        
class OrderAddressInfo(models.Model):
    '''Order address model'''
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="address_infos")
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)
    address_1 = models.CharField(max_length=50)
    address_2 = models.CharField(max_length=50,null=True,blank=True)
    town_city = models.CharField(max_length=100, null=True,blank=True)
    region = models.ForeignKey(Region,on_delete=models.DO_NOTHING, default=1)
    country = models.CharField(max_length=100, default="Ghana")
    gps = models.CharField(max_length=100, null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.order} - {self.address}'

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Order Address'
        verbose_name_plural = 'Order Addresses'

class Transaction(models.Model):
    def generate_transaction_id() -> str:
        '''Generates a unique transaction id'''
        sub = 'TR-'
        return sub + ''.join(random.choices(string.digits, k=8))
    STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Success', 'Success'),
        ('Failed', 'Failed'),
        ('Pending', 'Pending')
    )
    order = models.ForeignKey(Order, on_delete=models.PROTECT, related_name='transactions')
    transaction_id = models.CharField(max_length=20, default=generate_transaction_id, unique=True)
    transaction_status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.order} - {self.transaction_id} - {self.transaction_status}'
    
    class Meta:
        verbose_name_plural = 'Transactions'

website/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout

from accounts.models import User


class LoginView(View):
    template_name = 'account.html'
    def get(self,request):
        return render(request,self.template_name)
    
    def post(self,request):
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        user = authenticate(request,email=email,password=password)
        if user is not None:
            login(request,user)
            messages.success(request,'Logged in successfully')
            if user.is_customer:
                return redirect('website:home')
            elif user.is_admin:
                pass
            else:
                messages.info(request,'Unauthorized user')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            messages.info(request,'Invalid email or password')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        
class RegisterView(View):
    template_name = 'register.html'

    def get(self, request):
        context = {}
        return render(request, self.template_name, context)

    def post(self, request):
        first_name = request.POST.get('fname')
        last_name = request.POST.get('lname')
        gender = request.POST.get('gender')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')

        if password != confirm_password:
            messages.info(request, 'Passwords do not match')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


        email_exists = User.objects.filter(email=email).exists()
        print(email_exists)
        if email_exists:
            messages.info(request, 'User already exists')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        user = User.objects.create(
            first_name=first_name,
            last_name =last_name,
            email=email,
            phone_number=phone_number,
            gender=gender,
        )
        user.set_password(password)
        user.is_customer = True
        user.save()

        # Authenticate and log in the user
        user = authenticate(request, email=email, password=password)
        login(request, user)
        messages.success(request, 'Account created successfully')
        return redirect('website:home')
    
class LogoutView(View):
    def get(self,request):
        logout(request)
        messages.success(request,'Logged out successfully')
        return redirect('website:home')

website/templates/includes/modals/accounts.html
<!-- Log In Modal -->
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="loginmodal" aria-hidden="true">
    <div class="modal-dialog modal-xl login-pop-form" role="document">
        <div class="modal-content" id="loginmodal">
            <div class="modal-headers">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span class="ti-close"></span>
                </button>
            </div>

            <div class="modal-body p-5">
                <div class="text-center mb-4">
                    <h2 class="m-0 ft-regular" id="modal-title">Login or Register</h2>
                </div>

                <ul class="nav nav-tabs" id="loginRegisterTabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="login-tab" data-toggle="tab" href="#login-form" role="tab" aria-controls="login-form" aria-selected="true">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="register-tab" data-toggle="tab" href="#register-form" role="tab" aria-controls="register-form" aria-selected="false">Register</a>
                    </li>
                </ul>

                <div class="tab-content" id="loginRegisterContent">
                    <div class="tab-pane fade show active" id="login-form" role="tabpanel" aria-labelledby="login-tab">
                        <form action="{% url 'accounts:login' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group mt-3">
                                <label>Email</label>
                                <input type="email" class="form-control" placeholder="Email" name="email" required>
                            </div>

                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control" placeholder="Password" name="password" required>
                            </div>

                            <div class="form-group">
                                <div class="d-flex align-items-center justify-content-between">
                                    <div class="flex-1">
                                        <input id="dd" class="checkbox-custom" name="dd" type="checkbox">
                                        <label for="dd" class="checkbox-custom-label">Remember Me</label>
                                    </div>
                                    <div class="eltio_k2">
                                        <a href="#">Forgot Password?</a>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-md full-width bg-dark text-light fs-md ft-medium">Login</button>
                            </div>
                        </form>
                    </div>

                    <div class="tab-pane fade" id="register-form" role="tabpanel" aria-labelledby="register-tab">
                        <form action="{% url 'accounts:register' %}" method="post">
                            {% csrf_token %}
                            <div class="form-group mt-3">
                                <label>First Name</label>
                                <input type="text" class="form-control" placeholder="First Name" name="fname" required>
                            </div>
                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="text" class="form-control" placeholder="Last Name" name="lname" required>
                            </div>

                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" class="form-control" placeholder="Email" name="email" required>
                            </div>
                            <div class="form-group">
                                <label>Phone Number</label>
                                <input type="phone" class="form-control" placeholder="Phone Number" name="phone_number" required>
                            </div>
                            <div class="form-group">
                                <label>Gender </label>
                                <ul class="no-ul-list">
                                    <li>
                                        <input id="c1" class="radio-custom" name="gender" type="radio" value="Male">
                                        <label for="c1" class="radio-custom-label">Male</label>
                                    </li>
                                    <li>
                                        <input id="c2" class="radio-custom" name="gender" type="radio" value="Female">
                                        <label for="c2" class="radio-custom-label">Female</label>
                                    </li>
                                </ul>
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control" placeholder="Password" name="password" required>
                            </div>

                            <div class="form-group">
                                <label>Confirm Password</label>
                                <input type="password" class="form-control" placeholder="Confirm Password" name="confirm_password" required>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-md full-width bg-dark text-light fs-md ft-medium">Register</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Modal -->

website/templates/includes/modals/cart.html
<!-- Cart -->
<div class="w3-ch-sideBar w3-bar-block w3-card-2 w3-animate-right" style="display:none;right:0;" id="Cart">
    <div class="rightMenu-scroll">
        <div class="d-flex align-items-center justify-content-between slide-head py-3 px-3">
            <h4 class="cart_heading fs-md ft-medium mb-0">Products List</h4>
            <button onclick="closeCart()" class="close_slide"><i class="ti-close"></i></button>
        </div>
        <div class="right-ch-sideBar">

            {% if my_cart %}
            <div class="cart_select_items py-2">
                {% for item in my_cart %}
                <!-- Single Item -->
                <div class="d-flex align-items-center justify-content-between br-bottom px-3 py-3">
                    <div class="cart_single d-flex align-items-center">
                        <div class="cart_selected_single_thumb">
                            <a href="{% url 'website:product_details' item.product.id %}"><img src="{{item.product.get_image}}" width="60" class="img-fluid" alt="" /></a>
                        </div>
                        <div class="cart_single_caption pl-2">
                            <h4 class="product_title fs-sm ft-medium mb-0 lh-1">{{item.product.name}}</h4>
                            <p class="mb-2"><span class="text-dark ft-medium small">{{item.size}}</span>, <span class="text-dark small">{{item.color}}</span></p>
                            <h4 class="fs-md ft-medium mb-0 lh-1">GHC {{item.get_total}}</h4>
                        </div>
                    </div>
                    <div class="fls_last"><a href="{% url 'website:remove_item' item.id %}" class="close_slide gray"><i class="ti-close"></i></a></div>
                </div>
                {% endfor %}
            </div>

            <div class="d-flex align-items-center justify-content-between br-top br-bottom px-3 py-3">
                <h6 class="mb-0">Subtotal</h6>
                <h3 class="mb-0 ft-medium">GHC {{cart_sub_total}}</h3>
            </div>

            <div class="cart_action px-3 py-3">
                <div class="form-group">
                    <a href="{% url 'website:checkout' %}" class="btn d-block full-width btn-dark">Checkout Now</a>
                </div>
                <div class="form-group">
                    <a href="{% url 'website:my-cart' %}" class="btn d-block full-width btn-dark-light">Edit or View</a>
                </div>
            </div>
            {% else %}
            <div class="cart_select_items py-2 text-center">
                <p>Your cart is empty. Please add some items to your cart.</p>
                <a href="{% url 'website:collection' %}" class="btn btn-dark">Shop Now</a>
            </div>
            {% endif %}

        </div>
    </div>
</div>

website/templates/includes/modals/order_detail.html
<!-- Modal for order details -->

{% for order in order_history %}
<div class="modal fade" id="orderDetailsModal_{{ order.id }}" tabindex="-1" role="dialog" aria-labelledby="orderDetailsModal_{{ order.id }}Label" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="orderDetailsModal_{{ order.id }}Label">Order Details - {{order.order_id}}</h5>
                <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button> -->
            </div>
            <div class="modal-body" id="orderDetailsModal_{{ order.id }}Body">
               <div class="row">
                   <div class="col-lg-6 col-md-12 mb-3 mb-lg-3">
                       <div class="card">
                           <div class="card-body">
                               <h5 class="card-title">Order Details</h5>
                               <p class="card-text">
                                   <b>Order ID:</b> {{ order.order_id }}<br>
                                   <b>Full Name:</b> {{ order.user.get_full_name }}<br>
                                   <b>Amount:</b> GHC {{ order.total_price }}<br>
                                   <b>Status:</b>
                                   <span class="badge badge-{% if order.status == 'Pending' %}warning{% elif order.status == 'Processing' %}info{% elif order.status == 'Approved' %}success{% elif order.status == 'Shipped' %}primary{% elif order.status == 'Delivered' %}success{% elif order.status == 'Returned' %}danger{% elif order.status == 'Cancelled' %}secondary{% else %}danger{% endif %}">{{ order.status }}</span><br>
                                   <b>Payment Mode:</b> {{ order.payment_method }}<br>
                                   {% if order.address_infos %}
                                   <b>Mobile:</b> {{ order.address_infos.first.phone_number }}<br>
                                   {% endif %}
                                   <b>Date Ordered:</b> {{ order.created_at | date:"d M Y" }}
                               </p>
                           </div>
                       </div>
                   </div>
                   {% if order.payment_method == "Online" %}
                   <div class="col-lg-6 col-md-12 mb-3 mb-lg-3">
                       <div class="card">
                           <div class="card-body">
                               <h5 class="card-title">Payment Details</h5>
                               <p class="card-text">
                                   <b>Transaction ID:</b>
                                   <a href="#" class="text-primary">{{ order.payments.first.transaction_id }}</a><br>
                                   <b>Payment Status:</b>
                                   <span class="badge badge-{% if order.payments.first.payment_status == 'Pending' %}warning{% elif order.payments.first.payment_status == 'Paid' %}success{% else %}danger{% endif %}">{{ order.get_payment_status_display }}</span>
                               </p>
                           </div>
                       </div>
                   </div>
                   {% endif %}
                  {% if order.address_infos.exists %}
                      <div class="col-lg-6 col-md-12 mb-3 mb-lg-3">
                          <div class="card">
                              <div class="card-body">
                                  <h5 class="card-title">Delivery Address</h5>
                                  <p class="card-text">
                                      {{ order.address_infos.first.first_name }} {{ order.address_infos.first.last_name }}<br>
                                      {{ order.address_infos.first.address_1 }}<br>
                                      {% if order.address_infos.first.address_2 %}
                                      {{ order.address_infos.first.address_2 }}<br>
                                      {% endif %}
                                      {{ order.address_infos.first.town_city }}, {{ order.address_infos.first.region.name }}<br>
                                      {{ order.address_infos.first.country }}<br>
                                      {{ order.address_infos.first.phone_number }}
                                  </p>
                              </div>
                          </div>
                  </div>
                  {% endif %}
               </div>
           </div>
            <div class="modal-footer">
                {% if order.payments.exists and order.get_payment_status_display != "Paid" and order.payment_method == "Online" %}
                    <a href="#" class="btn btn-sm btn-success">Pay Now</a>
                {% endif %}
                <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}