Adombisege/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/urls.py
from django.urls import path

from .views import *
app_name = 'website'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),
    path('add_to_cart/', AddToCartView.as_view(), name='add_to_cart'),
    path('collection/', CollectionView.as_view(), name='collection'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('faq/', FaqView.as_view(), name='faq'),
    path('my-cart/', MyCartView.as_view(), name='my-cart'),
    path('my-cart/remove_item/<int:item_id>/', RemoveCartItemView.as_view(), name='remove_item'),
    path('my-cart/update_quantity/<int:item_id>/', UpdateQuantityView.as_view(), name='update_cart_item'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('checkout/place-order/', PlaceOrderView.as_view(), name='place_order'),
    path('checkout/complete_order/', CompleteOrderView.as_view(), name='complete_order'),
    path('paypal-return/', paypal_return, name='paypal_return'),
    path('paypal-cancel/', paypal_cancel, name='paypal_cancel'),
    path('user-dashboard/', UserDashboardView.as_view(), name='user_dashboard'),
    path('user-dashboard/profile_update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),
    path('product-details/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
]

website/models.py
from django.db import models

# Create your models here.

website/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.conf import settings
from paypalrestsdk import Payment
import paypalrestsdk
from django.views.decorators.csrf import csrf_exempt
from django.views import View
from django.views.generic import CreateView
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from Adombisege.utils.decorators import MustLogin
from dashboard.forms import OrderAddressForm
from dashboard.models import Contact, Order, OrderAddressInfo, OrderItems, Product, Category, Cart, Region
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth import update_session_auth_hash
from django.utils.decorators import method_decorator

# paypalrestsdk.configure({
#     "mode": settings.PAYPAL_MODE,  # sandbox or live
#     "client_id": settings.PAYPAL_CLIENT_ID,
#     "client_secret": settings.PAYPAL_CLIENT_SECRET,
# })

class HomePageView(View):
    template_name = 'pages/home.html'
    
    def get(self, request):
        categories = Category.objects.all()[:3]
        products = Product.objects.filter(category__in=categories, status= 'Published').order_by('-created_at')[:20]
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0 
        context = {
            'categories' : categories,
            'products' : products,
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
        }
        return render(request, self.template_name, context)
    
class SearchView(View):
    template_name = 'pages/search_result.html'
    
    def get(self, request):
        user = request.user
        keyword = request.GET.get('keyword')
        category_id = request.GET.get('category')
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        if keyword:
            products = Product.objects.filter(Q(name__icontains=keyword) | Q(description__icontains=keyword) | Q(category__id=category_id), status= 'Published') if category_id else Product.objects.filter(Q(name__icontains=keyword) | Q(description__icontains=keyword), status= 'Published')
            paginator = Paginator(products, 12)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            categories = Category.objects.all()
            my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
            context = {
                'products' : page_obj,
                'my_cart' : my_cart,
                'categories' : categories,
                'cart_sub_total' : cart_sub_total,
            }
            return render(request, self.template_name,context)
    
class CollectionView(View):
    template_name = 'pages/collection.html'
    
    def get(self, request):
        user = request.user
        sort_by = request.GET.get('sort_by')
        category_name = request.GET.get('category_name')
        category_id = Category.objects.get(name=category_name).id if category_name else None
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        if sort_by or category_id:
            products = Product.objects.filter(status= 'Published')
            if category_id:
                products = products.filter(category_id=category_id)
            if sort_by == 'price_low_to_high':
                products = products.order_by('regular_price')
            elif sort_by == 'price_high_to_low':
                products = products.order_by('-regular_price')
            elif sort_by == 'newest_first':
                products = products.order_by('-created_at')
            elif sort_by == 'oldest_first':
                products = products.order_by('created_at')
            paginator = Paginator(products, 12)
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            user = request.user
            my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
            categories = Category.objects.all()
            context = {
                'products' : page_obj,
                'my_cart' : my_cart,
                'categories' : categories,
                'cart_sub_total' : cart_sub_total,
            }
            return render(request, self.template_name,context)
        products = Product.objects.filter(status= 'Published').order_by('-created_at')
        paginator = Paginator(products, 20)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        categories = Category.objects.all()
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        context = {
            'products' : page_obj,
            'categories' : categories,
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
        }
        return render(request, self.template_name,context)
    

class ContactView(View):
    template_name = 'pages/contact.html'
    
    def get(self, request):
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
            'categories' : categories
        }
        return render(request, self.template_name,context)
    
    def post(self, request):
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        if name and email and subject and message:
            Contact.objects.create(name=name, email=email, subject=subject, message=message)
            messages.success(request, 'Your message has been sent successfully!')
            return redirect('website:contact') 
        else:
            messages.error(request, 'An error occurred while sending your message. Please ensure all fields are filled out correctly.')
        
        # In case of errors, re-render the page with the existing form data
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'my_cart': my_cart,
            'cart_sub_total': cart_sub_total,
            'categories': categories,
            'name': name,
            'email': email,
            'subject': subject,
            'message': message
        }
        return render(request, self.template_name, context)
class AboutUsView(View):
    template_name = 'pages/about-us.html'
    
    def get(self, request):
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
            'categories' : categories
        }
        return render(request, self.template_name,context)
    
class FaqView(View):
    template_name = 'pages/faq.html'
    
    def get(self, request):
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
            'categories' : categories
        }
        return render(request, self.template_name,context)
    
class PrivacyPolicyView(View):
    template_name = 'pages/privacy_policy.html'
    
    def get(self, request):
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
            'categories' : categories
        }
        return render(request, self.template_name,context)
    
class ProductDetailView(View):
    template_name = 'pages/product_details.html'
    
    def get(self, request, pk):
        product = Product.objects.get(id=pk)
        user = request.user
        my_cart = Cart.objects.filter(user=user) if user.is_authenticated else 0
        cart_sub_total = Cart.get_sub_total(user) if user.is_authenticated else 0
        categories = Category.objects.all()
        context = {
            'product' : product,
            'my_cart' : my_cart,
            'cart_sub_total' : cart_sub_total,
            'categories' : categories
        }
        return render(request, self.template_name,context)
    
class AddToCartView(View):
    @method_decorator(MustLogin)
    def post(self, request):
        user = request.user
        product_id = request.POST.get('product_id')
        size = request.POST.get('size')
        color = request.POST.get('color')
        quantity = int(request.POST.get('quantity'))
        product = Product.objects.get(id=product_id)
        # Check if the product is already in the user's cart
        cart_item = Cart.objects.filter(user=user, product=product).first()
        if cart_item:
            cart_item.quantity += quantity
            cart_item.save()
            messages.success(request, 'Product quantity updated successfully')

website/templates/includes/alerts.html
<div class="">
    <div class="container">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        <script>
            // Auto close the alert messages after 5 seconds
            setTimeout(function () {
                var alertDivs = document.querySelectorAll('.alert');
                alertDivs.forEach(function (alertDiv) {
                    alertDiv.remove();
                });
            }, 5000);
        </script>
    </div>
</div>

website/templates/includes/banner.html
{% load static  %}
<div class="home-slider hide-navigation margin-bottom-0">

    <!-- Slide -->
    <!-- Slide -->
    <div data-background-image="{% static 'website/assets/img/banner-a.jpg' %}" class="item" data-overlay="3">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="home-slider-container">

                        <!-- Slide Title -->
                        <div class="home-slider-desc text-center">
                            <div class="home-slider-title mb-4">
                                <h5 class="text-light fs-lg ft-medium mb-0">Winter Arrivals</h5>
                                <h1 class="mb-1 ft-bold lg-heading">Collections 2024</h1>
                            </div>

                            <p class="mb-0">
                                <a href="{% url 'website:collection' %}" class="btn stretched-link light-borders mx-2 my-3 ft-bold">Shop Men</a>
                                <a href="{% url 'website:collection' %}" class="btn stretched-link light-borders mx-2 my-3 ft-bold">Shop Women</a>
                            </p>

                        </div>
                        <!-- Slide Title / End -->

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Slide -->
    <!-- <div data-background-image="{% static 'website/assets/img/banner-b.jpg' %}" class="item">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="home-slider-container">

                        <div class="home-slider-desc">
                            <div class="home-slider-title mb-4">
                                <h5 class="text-light fs-md ft-medium mb-0">Summer Collection</h5>
                                <h1 class="mb-1 ft-bold text-light lg-heading">Women's Fashion<br>UpTo 30% Off</h1>
                                <span class="trending text-light">There's nothing like trend</span>
                            </div>

                            <a href="{% url 'website:collection' %}" class="btn btn-white stretched-link">Shop Now<i class="lni lni-arrow-right ml-2"></i></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div> -->

    <!-- Slide -->
    <!-- <div data-background-image="{% static 'website/assets/img/banner-c.jpg' %}" class="item" data-overlay="3">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="home-slider-container">

                        <div class="home-slider-desc text-center">
                            <div class="home-slider-title mb-4">
                                <h5 class="text-light fs-lg ft-medium mb-0">Get Summer Styles</h5>
                                <h1 class="mb-1 ft-bold lg-heading">UP TO 40% OFF</h1>
                                <span class="trending text-light">There's nothing like trend</span>
                            </div>

                            <a href="#" class="btn btn-white stretched-link">Shop Now<i class="lni lni-arrow-right ml-2"></i></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div> -->

</div>

website/templates/includes/footer.html
{% load static %}
<!-- ============================ Footer Start ================================== -->
<footer class="dark-footer skin-dark-footer style-2">
    <div class="footer-middle">
        <div class="container">
            <div class="row">

                <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
                    <div class="footer_widget">
                        <!-- <img src="{% static 'website/assets/img/logo-light.png' %}" class="img-footer small mb-2" alt="" /> -->
                        <div class="address mt-1">
                            Accra <br>Greater Accra Region, Ghana
                        </div>
                        <div class="address mt-2">
                            +233 53 758 1141<br>goldengrovecollections@hotmail.com
                        </div>
                        <div class="address mt-3">
                            <ul class="list-inline">
                                <li class="list-inline-item"><a href="#"><i class="lni lni-facebook-filled"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="lni lni-twitter-filled"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="lni lni-youtube"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="lni lni-instagram-filled"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="lni lni-linkedin-original"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12">
                    <div class="footer_widget">
                        <h4 class="widget_title">Supports</h4>
                        <ul class="footer-menu">
                            <li><a href="#">Collection</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">FAQs</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12">
                    <div class="footer_widget">
                        <h4 class="widget_title">Subscribe</h4>
                        <p>Receive updates, hot deals, discounts sent straignt in your inbox daily</p>
                        <div class="foot-news-last">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Email Address">
                                <div class="input-group-append">
                                    <button type="button" class="input-group-text b-0 text-light"><i class="lni lni-arrow-right"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12 col-md-12 text-center">
                    <p class="mb-0">Golden Grove Collections © {% now "Y" %} All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

website/templates/includes/header.html
{% load static %}
<div class="header header-light dark-text">
    <div class="container">
        <nav id="navigation" class="navigation navigation-landscape">
            <div class="nav-header">
                <a class="nav-brand" href="#">
                        <img src="{% static 'website/assets/img/logo.jpg' %}" class="logo" alt="" />
                    </a>
                    <div class="nav-toggle"></div>
                    <div class="mobile_nav">
                        <ul>
                            <li>
                                <a href="#" onclick="openSearch()">
                                    <i class="lni lni-search-alt"></i>
                                </a>
                            </li>
                            {% if request.user.is_authenticated %}
                                <li>
                                    <a href="#" onclick="openCart()">
                                        <i class="lni lni-shopping-basket"></i><span class="dn-counter">{{my_cart.count}}</span>
                                    </a>
                                </li>
                            {% endif %}
                            
                            <li>
                                <a href="{% url 'website:user_dashboard' %}" 
                                   {% if not request.user.is_authenticated %} 
                                       data-toggle="modal" data-target="#login" 
                                       href="#"
                                   {% endif %}>
                                    <i class="lni lni-user"></i>
                                </a>
                            </li>
                                
                        </ul>
                    </div>
            </div>
            <div class="nav-menus-wrapper" style="transition-property: none;">
                <ul class="nav-menu">

                    <li><a href="{% url 'website:home' %}">Home</a></li>
                    <li><a href="{% url 'website:collection' %}">Collection</a></li>
                    <li><a href="{% url 'website:about_us' %}">About</a></li>
                    <li><a href="{% url 'website:contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'website:faq' %}">Faqs</a></li>
                </ul>

                <ul class="nav-menu nav-menu-social align-to-right">
                    <li>
                        <a href="#" onclick="openSearch()">
                                <i class="lni lni-search-alt"></i>
                            </a>
                    </li>
                    
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="#" onclick="openCart()">
                            <i class="lni lni-shopping-basket"></i><span class="dn-counter">{{my_cart.count}}</span>
                        </a>
                    </li>
                    {% endif %}
                        
                    <li>
                        <a href="{% url 'website:user_dashboard' %}" 
                           {% if not request.user.is_authenticated %} 
                               data-toggle="modal" data-target="#login" 
                               href="#"
                           {% endif %}>
                            <i class="lni lni-user"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

website/templates/includes/scripts.html
{% load static %}
<script src="{% static 'website/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'website/assets/js/popper.min.js' %}"></script>
<script src="{% static 'website/assets/js/bootstrap.min.js' %}"></script>
<script src="{% static 'website/assets/js/ion.rangeSlider.min.js' %}"></script>
<script src="{% static 'website/assets/js/slick.js' %}"></script>
<script src="{% static 'website/assets/js/slider-bg.js' %}"></script>
<script src="{% static 'website/assets/js/lightbox.js' %}"></script>
<script src="{% static 'website/assets/js/smoothproducts.js' %}"></script>
<script src="{% static 'website/assets/js/snackbar.min.js' %}"></script>
<script src="{% static 'website/assets/js/jQuery.style.switcher.js' %}"></script>
<script src="{% static 'website/assets/js/custom.js' %}"></script>
<!-- ============================================================== -->
<!-- This page plugins -->
<!-- ============================================================== -->
<script>
    function openSearch() {
        document.getElementById("Search").style.display = "block";
    }
    function closeSearch() {
        document.getElementById("Search").style.display = "none";
    }
</script>
<script>
    function openCart() {
        document.getElementById("Cart").style.display = "block";
    }

    function closeCart() {
        document.getElementById("Cart").style.display = "none";
    }
</script>

website/templates/includes/top_header.html
<div class="py-2 gray hide-ipad">
    <div class="container">
        <div class="row">

            <div class="col-xl-4 col-lg-4 col-md-5 col-sm-6 hide-ipad">
                <div class="top_first"><a href="callto:(+233) 537581141" class="medium text-muted">(+233) 53 7581 141</a></div>
            </div>

            <div class="col-xl-4 col-lg-4 col-md-5 col-sm-12 hide-ipad">
                <div class="top_second text-center">
                    <p class="medium text-muted m-0 p-0">
                        Welcome to Golden Grove Collection
                    </p>
                </div>
            </div>

            <!-- Right Menu -->
            <div class="col-xl-4 col-lg-4 col-md-5 col-sm-6 hide-ipad">
                <div class="top_last text-right">
                    <div class="address">
                        <ul class="list-inline">
                            <li class="list-inline-item"><a href="#"><i class="lni lni-facebook-filled"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="lni lni-twitter-filled"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="lni lni-youtube"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="lni lni-instagram-filled"></i></a></li>
                            <li class="list-inline-item"><a href="#"><i class="lni lni-linkedin-original"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>